### ISSUE TITLE
Universal PlatformColor

### ISSUE THREAD

**Issue by cloudorbush** [heineiuo/react-native-platform-color#1]
Hi @heineiuo,

Awesome library.

It would be cool if we could combine all the logic in one `PlatformColor` so we don't have to import it twice everywhere.

Thanks!

**Comment by heineiuo** [comment]
@10000multiplier Thanks.

I can't catch your point, where did you imported it twice? Do you mean you have to import both 'react-native' and 'react-native-platform-color' ?

**Comment by cloudorbush** [comment]
@heineiuo yes, right now it looks like this:

```jsx
import { Platform, PlatformColor, StyleSheet } from 'react-native'
import { PlatformColor as WebPlatformColor } from 'react-native-platform-color'

StyleSheet.create({
  container: {
    flex: 1,
    ...Platform.select({
      ios: {
        backgroundColor: PlatformColor('systemBackground')
      },
	  android: {
	    backgroundColor: PlatformColor('@android:color/holo_blue_bright')
	  },
      default: {
        backgroundColor: WebPlatformColor('systemBackground')
      }
    })
  }
})
```

I guess it looks OK

**Comment by heineiuo** [comment]
@10000multiplier You do not need  `import { PlatformColor } from 'react-native'` because `WebPlatformColor` will check `Platform`:

https://github.com/heineiuo/react-native-platform-color/blob/95211e191a4f7d1a79f4a5bd3948e4fb4ba52db7/src/PlatformColor.tsx#L391-L397

**Comment by heineiuo** [comment]
> ```js
> import { Platform, PlatformColor, StyleSheet } from 'react-native'
> import { PlatformColor as WebPlatformColor } from 'react-native-platform-color'
> 
> StyleSheet.create({
>   container: {
>     flex: 1,
>     ...Platform.select({
>       ios: {
>         backgroundColor: PlatformColor('systemBackground')
>       },
> 	  android: {
> 	    backgroundColor: PlatformColor('@android:color/holo_blue_bright')
> 	  },
>       default: {
>         backgroundColor: WebPlatformColor('systemBackground')
>       }
>     })
>   }
> })
> ```

So this can be simplified to 

```jsx

import { Platform, StyleSheet } from 'react-native'
import { PlatformColor } from 'react-native-platform-color'

StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Platform.select({
      android: PlatformColor('@android:color/holo_blue_bright'),
      default: PlatformColor('systemBackground')
    })
  }
})

```

**Comment by cloudorbush** [comment]
Ah awesome. 

thank you!
